# Generated by Django 4.0.4 on 2022-05-25 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.SlugField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Date_of_birth', models.DateField()),
                ('Full_name', models.CharField(max_length=255)),
                ('Wallet_balance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expenses_Types',
            fields=[
                ('Expenses_types_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=255)),
                ('Name_of_expenses_types', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('Limits_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount_of_limit', models.IntegerField()),
                ('Date_time_gap', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('Expenses_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('Expense_Date', models.DateTimeField(auto_now_add=True)),
                ('Client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
                ('Expenses_types_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.expenses_types')),
                ('Limits_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.limits')),
            ],
        ),
    ]
